const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('api', {
  pickVideos: () => ipcRenderer.invoke('pick-videos'),
  saveSessionAs: (data) => ipcRenderer.invoke('save-session-as', data),
  saveSessionTo: (filePath, data) => ipcRenderer.invoke('save-session-to', filePath, data),
  loadSession: (filePath) => ipcRenderer.invoke('load-session', filePath || null),
  fileExists: (p) => ipcRenderer.invoke('file-exists', p),
  getPathForFile: (file) => webUtils.getPathForFile(file),
  videoUrl: (p) => 'localvideo://v/' + Buffer.from(p, 'utf8').toString('base64url'),
  onOpenSession: (cb) => ipcRenderer.on('open-session', (_e, p) => cb(p)),
  probe: (p) => ipcRenderer.invoke('probe', p),
  makeProxy: (p) => ipcRenderer.invoke('make-proxy', p),
  cancelProxy: (p) => ipcRenderer.send('cancel-proxy', p),
  onProxyProgress: (cb) => ipcRenderer.on('proxy-progress', (_e, p, frac) => cb(p, frac)),
  cacheInfo: () => ipcRenderer.invoke('cache-info'),
  clearCache: () => ipcRenderer.invoke('clear-cache'),
  parent: () => ipcRenderer.invoke('twitch-parent'),
  version: () => ipcRenderer.invoke('app-version'),
  webThumb: (id) => ipcRenderer.invoke('web-thumb', id),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (s) => ipcRenderer.invoke('save-settings', s),
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  listFolder: (dir) => ipcRenderer.invoke('list-folder', dir),
  thumb: (p) => ipcRenderer.invoke('thumb', p),
  listPlaylist: (u) => ipcRenderer.invoke('list-playlist', u),
  updateYtdlp: () => ipcRenderer.invoke('update-ytdlp'),
  ytdlpAvailable: () => ipcRenderer.invoke('ytdlp-available'),
  showInExplorer: (p) => ipcRenderer.invoke('show-in-explorer', p),
  copyText: (t) => ipcRenderer.invoke('copy-text', t),
  // image sequences (frame player)
  sequenceFor: (p) => ipcRenderer.invoke('sequence-for', p),
  seqInfo: (dir, seq) => ipcRenderer.invoke('seq-info', dir, seq),
  framesDir: () => ipcRenderer.invoke('frames-dir'),
  framesOnDisk: (key) => ipcRenderer.invoke('frames-on-disk', key),
  ensureFrames: (req) => ipcRenderer.send('ensure-frames', req),
  cancelFrames: (key) => ipcRenderer.send('cancel-frames', key),
  onFramesReady: (cb) => ipcRenderer.on('frames-ready', (_e, key, from, to) => cb(key, from, to)),
  onFramesFailed: (cb) => ipcRenderer.on('frames-failed', (_e, key, from, to, msg) => cb(key, from, to, msg)),
  ffmpegHas: (name) => ipcRenderer.invoke('ffmpeg-has', name),
});
